plugins:
  - serverless-offline
  - serverless-webpack

service: onestep-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-1

functions:
  onestep:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{any+}
          method: ANY

custom:
  webpack:
    webpackConfig: "webpack.config.js"
